import { mysqlTable, mysqlSchema, AnyMySqlColumn, int, varchar, text, char, smallint, longtext, unique, index } from "drizzle-orm/mysql-core"
import { sql } from "drizzle-orm"

export const bank = mysqlTable("bank", {
	bankId: int("bank_id").autoincrement().notNull(),
	name: varchar({ length: 128 }).notNull(),
	noRek: varchar("no_rek", { length: 128 }).notNull(),
	owner: varchar({ length: 128 }).notNull(),
	createBy: int("create_by").notNull(),
});

export const botTelegram = mysqlTable("bot_telegram", {
	id: int().autoincrement().notNull(),
	token: varchar({ length: 128 }).notNull(),
	usernameBot: varchar("username_bot", { length: 128 }).notNull(),
	usernameOwner: varchar("username_owner", { length: 128 }).notNull(),
	idTelegramOwner: varchar("id_telegram_owner", { length: 128 }).notNull(),
	idGroupTeknisi: varchar("id_group_teknisi", { length: 50 }).notNull(),
	createBy: int("create_by").notNull(),
});

export const catExpenditure = mysqlTable("cat_expenditure", {
	categoryId: int("category_id").autoincrement().notNull(),
	name: varchar({ length: 50 }).notNull(),
	remark: text().notNull(),
	createBy: int("create_by").notNull(),
});

export const catIncome = mysqlTable("cat_income", {
	categoryId: int("category_id").autoincrement().notNull(),
	name: varchar({ length: 50 }).notNull(),
	remark: text().notNull(),
	createBy: int("create_by").notNull(),
});

export const company = mysqlTable("company", {
	id: int().notNull(),
	companyName: varchar("company_name", { length: 100 }).notNull(),
	subName: varchar("sub_name", { length: 128 }).notNull(),
	description: text().notNull(),
	picture: text().notNull(),
	logo: text().notNull(),
	whatsapp: varchar({ length: 100 }).notNull(),
	facebook: varchar({ length: 100 }).notNull(),
	twitter: varchar({ length: 100 }).notNull(),
	instagram: varchar({ length: 100 }).notNull(),
	phone: varchar({ length: 100 }).notNull(),
	email: varchar({ length: 100 }).notNull(),
	owner: varchar({ length: 128 }).notNull(),
	video: text().notNull(),
	address: text().notNull(),
	dueDate: int("due_date").notNull(),
	ppn: int().notNull(),
	adminFee: int("admin_fee").notNull(),
	terms: text().notNull(),
	policy: text().notNull(),
	expired: varchar({ length: 50 }).notNull(),
	isolir: int().notNull(),
	import: int().notNull(),
	appsName: varchar("apps_name", { length: 20 }).notNull(),
	cekBill: int("cek_bill").notNull(),
	cekUsage: int("cek_usage").notNull(),
	latitude: text().notNull(),
	longitude: text().notNull(),
	phonecode: int().notNull(),
	country: int().notNull(),
	currency: varchar({ length: 50 }).notNull(),
	timezone: varchar({ length: 50 }).notNull(),
	tawk: text().notNull(),
	speedtest: text().notNull(),
	maintenance: int().notNull(),
	watermark: int().notNull(),
	version: text().notNull(),
	lastUpdate: text("last_update").notNull(),
	bcava: text().notNull(),
	licence: text().notNull(),
});

export const confirmPayment = mysqlTable("confirm_payment", {
	confirmId: int("confirm_id").autoincrement().notNull(),
	invoiceId: int("invoice_id").notNull(),
	noServices: varchar("no_services", { length: 25 }).notNull(),
	metodePayment: varchar("metode_payment", { length: 50 }).notNull(),
	datePayment: varchar("date_payment", { length: 50 }).notNull(),
	status: varchar({ length: 20 }).notNull(),
	remark: text().notNull(),
	dateCreated: int("date_created").notNull(),
	picture: text().notNull(),
});

export const country = mysqlTable("country", {
	id: int().autoincrement().notNull(),
	iso: char({ length: 2 }).notNull(),
	name: varchar({ length: 80 }).notNull(),
	nicename: varchar({ length: 80 }).notNull(),
	iso3: char({ length: 3 }).default('NULL'),
	numcode: smallint().default('NULL'),
	phonecode: int().notNull(),
});

export const coupon = mysqlTable("coupon", {
	couponId: int("coupon_id").autoincrement().notNull(),
	code: varchar({ length: 20 }).notNull(),
	isActive: int("is_active").notNull(),
	percent: int().notNull(),
	oneTime: int("one_time").notNull(),
	maxActive: int("max_active").notNull(),
	maxLimit: int("max_limit").notNull(),
	created: int().notNull(),
	expired: varchar({ length: 50 }).notNull(),
	remark: text().notNull(),
	createBy: int("create_by").notNull(),
});

export const coverage = mysqlTable("coverage", {
	coverageId: int("coverage_id").autoincrement().notNull(),
	cName: varchar("c_name", { length: 128 }).notNull(),
	address: text().notNull(),
	idProv: varchar("id_prov", { length: 50 }).notNull(),
	idKab: varchar("id_kab", { length: 50 }).notNull(),
	idKec: varchar("id_kec", { length: 50 }).notNull(),
	idKel: varchar("id_kel", { length: 50 }).notNull(),
	comment: text().notNull(),
	latitude: text().notNull(),
	longitude: text().notNull(),
	radius: int().notNull(),
	public: int().notNull(),
	codeArea: int("code_area").notNull(),
	createBy: int("create_by").notNull(),
	coverageMitra: int("coverage_mitra").notNull(),
});

export const coverOperator = mysqlTable("cover_operator", {
	id: int().autoincrement().notNull(),
	roleId: int("role_id").notNull(),
	coverageId: int("coverage_id").notNull(),
	operator: int().notNull(),
	createBy: int("create_by").notNull(),
});

export const coverPackage = mysqlTable("cover_package", {
	id: int().autoincrement().notNull(),
	coverageId: int("coverage_id").notNull(),
	packageId: int("package_id").notNull(),
	created: int().notNull(),
	createBy: int("create_by").notNull(),
});

export const currencies = mysqlTable("currencies", {
	code: varchar({ length: 15 }).notNull(),
	name: varchar({ length: 100 }).notNull(),
	number: char({ length: 5 }).notNull(),
	subunitsInUnit: int("subunits_in_unit").notNull(),
	countries: longtext().notNull(),
});

export const customer = mysqlTable("customer", {
	customerId: int("customer_id").autoincrement().notNull(),
	name: varchar({ length: 128 }).notNull(),
	noServices: varchar("no_services", { length: 128 }).notNull(),
	email: varchar({ length: 128 }).notNull(),
	registerDate: varchar("register_date", { length: 50 }).notNull(),
	dueDate: int("due_date").notNull(),
	address: text().notNull(),
	noWa: varchar("no_wa", { length: 128 }).notNull(),
	cStatus: varchar("c_status", { length: 128 }).notNull(),
	ppn: int().notNull(),
	noKtp: varchar("no_ktp", { length: 128 }).notNull(),
	ktp: text().notNull(),
	created: int().notNull(),
	modeUser: varchar("mode_user", { length: 50 }).notNull(),
	userMikrotik: varchar("user_mikrotik", { length: 128 }).notNull(),
	mitra: int().notNull(),
	coverage: int().notNull(),
	autoIsolir: int("auto_isolir").notNull(),
	typeId: varchar("type_id", { length: 50 }).notNull(),
	router: int().notNull(),
	codeunique: int().notNull(),
	phonecode: int().notNull(),
	latitude: text().notNull(),
	longitude: text().notNull(),
	userProfile: varchar("user_profile", { length: 50 }).notNull(),
	action: int().notNull(),
	typePayment: int("type_payment").notNull(),
	maxDueIsolir: int("max_due_isolir").notNull(),
	olt: int().notNull(),
	connection: int().notNull(),
	custAmount: int("cust_amount").notNull(),
	macAddress: varchar("mac_address", { length: 50 }).notNull(),
	level: int().notNull(),
	custDescription: text("cust_description").notNull(),
	typeIp: int("type_ip").notNull(),
	idOdc: int("id_odc").notNull(),
	idOdp: int("id_odp").notNull(),
	noPortOdp: int("no_port_odp").notNull(),
	monthDueDate: int("month_due_date").notNull(),
	sendBill: int("send_bill").notNull(),
	serialNumber: text("serial_number").notNull(),
	passMikrotik: text("pass_mikrotik").notNull(),
	slot: int().notNull(),
	port: int().notNull(),
	onuIndex: int("onu_index").notNull(),
	onuType: text("onu_type").notNull(),
	vlan: int().notNull(),
	noVa: text("no_va").notNull(),
	upOnu: text("up_onu").notNull(),
	downOnu: text("down_onu").notNull(),
	customerMitra: int("customer_mitra").notNull(),
	createby: int().notNull(),
});

export const customerChart = mysqlTable("customer_chart", {
	id: int().autoincrement().notNull(),
	idChart: varchar("id_chart", { length: 50 }).notNull(),
	fromcs: varchar({ length: 50 }).notNull(),
	tocs: varchar({ length: 128 }).notNull(),
	type: varchar({ length: 50 }).notNull(),
});

export const customerLine = mysqlTable("customer_line", {
	id: int().autoincrement().notNull(),
	idLine: varchar("id_line", { length: 50 }).notNull(),
	customerId: varchar("customer_id", { length: 50 }).notNull(),
	width: int().notNull(),
	height: int().notNull(),
	dir: varchar({ length: 50 }).notNull(),
});

export const customerStatus = mysqlTable("customer_status", {
	id: int().autoincrement().notNull(),
	status: text().notNull(),
	remark: text().notNull(),
	activeBill: int("active_bill").notNull(),
});

export const customerUsage = mysqlTable("customer_usage", {
	id: int().autoincrement().notNull(),
	noServices: varchar("no_services", { length: 50 }).notNull(),
	countUsage: varchar("count_usage", { length: 100 }).notNull(),
	dateUsage: varchar("date_usage", { length: 50 }).notNull(),
	lastUpdate: varchar("last_update", { length: 40 }).notNull(),
});

export const email = mysqlTable("email", {
	id: int().notNull(),
	protocol: varchar({ length: 50 }).notNull(),
	host: varchar({ length: 50 }).notNull(),
	email: varchar({ length: 50 }).notNull(),
	password: varchar({ length: 50 }).notNull(),
	port: varchar({ length: 50 }).notNull(),
	name: varchar({ length: 50 }).notNull(),
	sendPayment: int("send_payment").notNull(),
	sendVerify: int("send_verify").notNull(),
	forgotPassword: int("forgot_password").notNull(),
	textCreate: text("text_create").notNull(),
	textPay: text("text_pay").notNull(),
	textVerify: text("text_verify").notNull(),
	textForgot: text("text_forgot").notNull(),
	createInvoice: int("create_invoice").notNull(),
});

export const expenditure = mysqlTable("expenditure", {
	expenditureId: int("expenditure_id").autoincrement().notNull(),
	datePayment: varchar("date_payment", { length: 125 }).notNull(),
	nominal: varchar({ length: 125 }).notNull(),
	remark: text().notNull(),
	created: int().notNull(),
	category: int().notNull(),
	createBy: int("create_by").notNull(),
});

export const help = mysqlTable("help", {
	id: int().autoincrement().notNull(),
	noTicket: varchar("no_ticket", { length: 50 }).notNull(),
	helpType: int("help_type").notNull(),
	helpSolution: int("help_solution").notNull(),
	noServices: varchar("no_services", { length: 50 }).notNull(),
	description: text().notNull(),
	dateCreated: int("date_created").notNull(),
	status: varchar({ length: 50 }).notNull(),
	teknisi: int().notNull(),
	picture: text().notNull(),
	createBy: int("create_by").notNull(),
	action: int().notNull(),
	estimation: int().notNull(),
	ticketPassword: text("ticket_password").notNull(),
});

export const helpAction = mysqlTable("help_action", {
	id: int().autoincrement().notNull(),
	action: text().notNull(),
});

export const helpSolution = mysqlTable("help_solution", {
	hsId: int("hs_id").autoincrement().notNull(),
	hsHelpId: int("hs_help_id").notNull(),
	hsName: varchar("hs_name", { length: 110 }).notNull(),
	solution: text().notNull(),
});

export const helpTimeline = mysqlTable("help_timeline", {
	htId: int("ht_id").autoincrement().notNull(),
	helpId: int("help_id").notNull(),
	dateUpdate: int("date_update").notNull(),
	remark: text().notNull(),
	teknisi: int().notNull(),
	status: varchar({ length: 50 }).notNull(),
	dateCreated: varchar("date_created", { length: 40 }).notNull(),
	action: text().notNull(),
});

export const helpType = mysqlTable("help_type", {
	helpId: int("help_id").autoincrement().notNull(),
	helpType: varchar("help_type", { length: 50 }).notNull(),
	helpRemark: text("help_remark").notNull(),
});

export const income = mysqlTable("income", {
	incomeId: int("income_id").autoincrement().notNull(),
	datePayment: varchar("date_payment", { length: 125 }).notNull(),
	nominal: varchar({ length: 125 }).notNull(),
	remark: text().notNull(),
	created: int().notNull(),
	category: int().notNull(),
	createBy: int("create_by").notNull(),
	invoiceId: int("invoice_id").notNull(),
	noServices: varchar("no_services", { length: 50 }).notNull(),
	modePayment: varchar("mode_payment", { length: 50 }).notNull(),
	picture: text().notNull(),
	coverage: int().notNull(),
});

export const invoice = mysqlTable("invoice", {
	invoiceId: int("invoice_id").autoincrement().notNull(),
	invoice: varchar({ length: 128 }).notNull(),
	codeUnique: int("code_unique").notNull(),
	month: varchar({ length: 11 }).notNull(),
	year: int().notNull(),
	noServices: varchar("no_services", { length: 128 }).notNull(),
	status: varchar({ length: 128 }).notNull(),
	iPpn: int("i_ppn").notNull(),
	created: int().notNull(),
	createBy: int("create_by").notNull(),
	datePayment: int("date_payment").default('NULL'),
	metodePayment: varchar("metode_payment", { length: 100 }).notNull(),
	adminFee: int("admin_fee").notNull(),
	amount: int().notNull(),
	orderId: varchar("order_id", { length: 128 }).notNull(),
	token: text().notNull(),
	paymentType: varchar("payment_type", { length: 128 }).notNull(),
	transactionTime: varchar("transaction_time", { length: 50 }).notNull(),
	bank: varchar({ length: 50 }).notNull(),
	vaNumber: varchar("va_number", { length: 50 }).notNull(),
	pdfUrl: text("pdf_url").notNull(),
	statusCode: varchar("status_code", { length: 5 }).notNull(),
	expired: text().notNull(),
	xId: varchar("x_id", { length: 128 }).notNull(),
	xBankCode: varchar("x_bank_code", { length: 128 }).notNull(),
	xMethod: varchar("x_method", { length: 50 }).notNull(),
	xAccountNumber: varchar("x_account_number", { length: 50 }).notNull(),
	xExpired: varchar("x_expired", { length: 50 }).notNull(),
	xExternalId: varchar("x_external_id", { length: 50 }).notNull(),
	xAmount: varchar("x_amount", { length: 50 }).notNull(),
	xQrcode: text("x_qrcode").notNull(),
	reference: text().notNull(),
	paymentUrl: text("payment_url").notNull(),
	codeCoupon: varchar("code_coupon", { length: 50 }).notNull(),
	discCoupon: int("disc_coupon").notNull(),
	outlet: int().notNull(),
	statusIncome: varchar("status_income", { length: 40 }).notNull(),
	invDueDate: varchar("inv_due_date", { length: 40 }).notNull(),
	dateIsolir: varchar("date_isolir", { length: 50 }).notNull(),
	sendBeforeDue: varchar("send_before_due", { length: 50 }).notNull(),
	sendDue: varchar("send_due", { length: 50 }).notNull(),
	picture: text().notNull(),
	invPpn: int("inv_ppn").notNull(),
	picture1: text().notNull(),
	sendBill: varchar("send_bill", { length: 50 }).notNull(),
	sendPaid: varchar("send_paid", { length: 50 }).notNull(),
	datePaid: varchar("date_paid", { length: 50 }).notNull(),
	sendBillEmail: text("send_bill_email").notNull(),
	sendBillSms: text("send_bill_sms").notNull(),
	sendPaidEmail: text("send_paid_email").notNull(),
	sendPaidSms: text("send_paid_sms").notNull(),
	subtotal: int().notNull(),
	amountuniq: int().notNull(),
	daterequniq: int().notNull(),
},
(table) => [
	unique("invoice").on(table.invoice),
]);

export const invoiceDetail = mysqlTable("invoice_detail", {
	detailId: int("detail_id").autoincrement().notNull(),
	invoiceId: varchar("invoice_id", { length: 128 }).notNull(),
	price: varchar({ length: 125 }).notNull(),
	qty: varchar({ length: 125 }).notNull(),
	disc: varchar({ length: 128 }).notNull(),
	remark: text().notNull(),
	total: varchar({ length: 128 }).notNull(),
	itemId: int("item_id").notNull(),
	categoryId: int("category_id").notNull(),
	dMonth: int("d_month").notNull(),
	dYear: int("d_year").notNull(),
	dNoServices: varchar("d_no_services", { length: 50 }).notNull(),
},
(table) => [
	index("invoice_id").on(table.invoiceId),
	index("category_id").on(table.categoryId),
	index("item_id").on(table.itemId),
]);

export const logs = mysqlTable("logs", {
	logId: int("log_id").autoincrement().notNull(),
	name: varchar({ length: 50 }).notNull(),
	datetime: int().notNull(),
	dateLog: varchar("date_log", { length: 40 }).notNull(),
	category: varchar({ length: 128 }).notNull(),
	roleId: int("role_id").notNull(),
	userId: int("user_id").notNull(),
	remark: text().notNull(),
});

export const maps = mysqlTable("maps", {
	id: int().autoincrement().notNull(),
	vendor: text().notNull(),
	token: text().notNull(),
});

export const modem = mysqlTable("modem", {
	id: int().autoincrement().notNull(),
	type: int().notNull(),
	name: varchar({ length: 50 }).notNull(),
	customerId: int("customer_id").notNull(),
	showCustomer: int("show_customer").notNull(),
	ipLocal: text("ip_local").notNull(),
	ipPublic: text("ip_public").notNull(),
	ssidName: varchar("ssid_name", { length: 50 }).notNull(),
	ssidPassword: varchar("ssid_password", { length: 50 }).notNull(),
	loginUser: varchar("login_user", { length: 50 }).notNull(),
	loginPassword: varchar("login_password", { length: 50 }).notNull(),
	remark: text().notNull(),
	created: int().notNull(),
	createby: int().notNull(),
	updated: int().notNull(),
	updateby: int().notNull(),
});

export const moota = mysqlTable("moota", {
	id: int().autoincrement().notNull(),
	isActive: int("is_active").notNull(),
	token: text().notNull(),
	sendWhatsapp: text("send_whatsapp").notNull(),
	sendTelegram: text("send_telegram").notNull(),
	secret: text().notNull(),
	noWhatsapp: text("no_whatsapp").notNull(),
	textIncome: text("text_income").notNull(),
	textExpend: text("text_expend").notNull(),
	changeBill: int("change_bill").notNull(),
});

export const mBrandDevice = mysqlTable("m_brand_device", {
	id: int().autoincrement().notNull(),
	onuType: int("onu_type").notNull(),
	name: text().notNull(),
	remark: text().notNull(),
	created: int().notNull(),
});

export const mOdc = mysqlTable("m_odc", {
	idOdc: int("id_odc").autoincrement().notNull(),
	codeOdc: text("code_odc").notNull(),
	coverageOdc: int("coverage_odc").notNull(),
	noPortOlt: int("no_port_olt").notNull(),
	colorTubeFo: text("color_tube_fo").notNull(),
	noPole: text("no_pole").notNull(),
	latitude: text().notNull(),
	longitude: text().notNull(),
	totalPort: int("total_port").notNull(),
	document: text().notNull(),
	remark: text().notNull(),
	created: int().notNull(),
	createBy: int("create_by").notNull(),
	roleId: int("role_id").notNull(),
});

export const mOdp = mysqlTable("m_odp", {
	idOdp: int("id_odp").autoincrement().notNull(),
	codeOdp: text("code_odp").notNull(),
	codeOdc: int("code_odc").notNull(),
	coverageOdp: int("coverage_odp").notNull(),
	noPortOdc: int("no_port_odc").notNull(),
	colorTubeFo: text("color_tube_fo").notNull(),
	noPole: text("no_pole").notNull(),
	latitude: text().notNull(),
	longitude: text().notNull(),
	totalPort: int("total_port").notNull(),
	document: text().notNull(),
	remark: text().notNull(),
	created: int().notNull(),
	createBy: int("create_by").notNull(),
	roleId: int("role_id").notNull(),
});

export const olt = mysqlTable("olt", {
	id: int().autoincrement().notNull(),
	isActive: int("is_active").notNull(),
	ipAddress: text("ip_address").notNull(),
	alias: varchar({ length: 40 }).notNull(),
	vendor: varchar({ length: 50 }).notNull(),
	username: varchar({ length: 50 }).notNull(),
	password: varchar({ length: 50 }).notNull(),
	value: varchar({ length: 40 }).notNull(),
	token: text().notNull(),
	bridgeOlt: text("bridge_olt").notNull(),
	port: int().notNull(),
	type: text().notNull(),
});

export const other = mysqlTable("other", {
	id: int().autoincrement().notNull(),
	sayWa: text("say_wa").notNull(),
	bodyWa: text("body_wa").notNull(),
	footerWa: text("footer_wa").notNull(),
	thanksWa: text("thanks_wa").notNull(),
	addCustomer: text("add_customer").notNull(),
	codeUnique: int("code_unique").notNull(),
	textCodeUnique: text("text_code_unique").notNull(),
	remarkInvoice: text("remark_invoice").notNull(),
	dateReset: int("date_reset").notNull(),
	dateCreate: int("date_create").notNull(),
	dateReminder: int("date_reminder").notNull(),
	keyApps: varchar("key_apps", { length: 50 }).notNull(),
	resetPassword: text("reset_password").notNull(),
	codeOtp: text("code_otp").notNull(),
	schIsolir: int("sch_isolir").notNull(),
	schCreatebill: int("sch_createbill").notNull(),
	schUsage: int("sch_usage").notNull(),
	schResetUsage: int("sch_reset_usage").notNull(),
	schBeforeDue: int("sch_before_due").notNull(),
	schDue: int("sch_due").notNull(),
	schResend: int("sch_resend").notNull(),
	invThermal: int("inv_thermal").notNull(),
	checkout: text().notNull(),
	createHelp: text("create_help").notNull(),
	createHelpCustomer: text("create_help_customer").notNull(),
	frontend: int().notNull(),
	showentri: int().notNull(),
	schBackup: int("sch_backup").notNull(),
	sizeThermal: int("size_thermal").notNull(),
	textHelpCustomer: text("text_help_customer").notNull(),
	versiMenu: int("versi_menu").notNull(),
	defaultLang: text("default_lang").notNull(),
	lastExGenerate: text("last_ex_generate").notNull(),
	lastExIsolir: text("last_ex_isolir").notNull(),
	lastExUsage: text("last_ex_usage").notNull(),
	lastExBackup: text("last_ex_backup").notNull(),
	textIsolir: text("text_isolir").notNull(),
	schRouter: text("sch_router").notNull(),
	package: text().notNull(),
});

export const package = mysqlTable("package", {
	id: int().notNull(),
	paymentGateway: int("payment_gateway").notNull(),
	router: int().notNull(),
	countRouter: int("count_router").notNull(),
	countCustomer: int("count_customer").notNull(),
	telegramBot: int("telegram_bot").notNull(),
	waGateway: int("wa_gateway").notNull(),
	maps: int().notNull(),
	chart: int().notNull(),
	mitra: int().notNull(),
	invoiceCustom: int("invoice_custom").notNull(),
	invoiceNo: int("invoice_no").notNull(),
	coverageOperator: int("coverage_operator").notNull(),
	coverageTeknisi: int("coverage_teknisi").notNull(),
	modem: int().notNull(),
	coveragePackage: int("coverage_package").notNull(),
	olt: int().notNull(),
	countOlt: int("count_olt").notNull(),
	absensi: int().notNull(),
	briva: int().notNull(),
	smsGateway: int("sms_gateway").notNull(),
	moota: int().notNull(),
	bcava: int().notNull(),
});

export const packageCategory = mysqlTable("package_category", {
	pCategoryId: int("p_category_id").autoincrement().notNull(),
	name: varchar({ length: 125 }).notNull(),
	description: text().notNull(),
	dateCreated: int("date_created").notNull(),
	dateUpdated: int("date_updated").notNull(),
	createBy: int("create_by").notNull(),
});

export const packageItem = mysqlTable("package_item", {
	pItemId: int("p_item_id").autoincrement().notNull(),
	name: varchar({ length: 125 }).notNull(),
	price: varchar({ length: 125 }).notNull(),
	picture: text().notNull(),
	description: text().notNull(),
	categoryId: int("category_id").notNull(),
	dateCreated: int("date_created").notNull(),
	dateUpdate: int("date_update").notNull(),
	public: int().notNull(),
	isActive: int("is_active").notNull(),
	createBy: int("create_by").notNull(),
	roleId: int("role_id").notNull(),
	packageMitra: int("package_mitra").notNull(),
},
(table) => [
	index("category_id").on(table.categoryId),
]);

export const paymentGateway = mysqlTable("payment_gateway", {
	id: int().notNull(),
	vendor: varchar({ length: 50 }).notNull(),
	apiKey: text("api_key").notNull(),
	serverKey: text("server_key").notNull(),
	clientKey: text("client_key").notNull(),
	isActive: int("is_active").notNull(),
	mode: int().notNull(),
	expired: int().notNull(),
	bcaVa: int("bca_va").notNull(),
	briVa: int("bri_va").notNull(),
	bniVa: int("bni_va").notNull(),
	kodemerchant: text().notNull(),
	mandiriVa: int("mandiri_va").notNull(),
	cimbVa: int("cimb_va").notNull(),
	mybankVa: int("mybank_va").notNull(),
	ovo: int().notNull(),
	permataVa: int("permata_va").notNull(),
	gopay: int().notNull(),
	shopeepay: int().notNull(),
	indomaret: int().notNull(),
	alfamart: int().notNull(),
	adminFee: int("admin_fee").notNull(),
	va: int().notNull(),
	ewallet: int().notNull(),
	retail: int().notNull(),
	qrcode: int().notNull(),
	alfamidi: int().notNull(),
	muamalatVa: int("muamalat_va").notNull(),
	sinarmasVa: int("sinarmas_va").notNull(),
	dana: int().notNull(),
	linkaja: int().notNull(),
});

export const paymentGatewayTransaction = mysqlTable("payment_gateway_transaction", {
	id: int().autoincrement().notNull(),
	vendor: text().notNull(),
	externalId: text("external_id").notNull(),
	method: text().notNull(),
	codeNumber: text("code_number").notNull(),
	customerId: text("customer_id").notNull(),
	noServices: text("no_services").notNull(),
	invoice: text().notNull(),
	reference: text().notNull(),
	paymentUrl: text("payment_url").notNull(),
	transactionTime: text("transaction_time").notNull(),
	dateCreated: text("date_created").notNull(),
});

export const product = mysqlTable("product", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 225 }).notNull(),
	picture: text().notNull(),
	remark: text().notNull(),
	link: text().notNull(),
	description: text().notNull(),
	dateCreated: int("date_created").notNull(),
	createBy: int("create_by").notNull(),
});

export const promo = mysqlTable("promo", {
	promoId: int("promo_id").autoincrement().notNull(),
	name: text().notNull(),
	picture: text().notNull(),
	remark: text().notNull(),
	slug: text().notNull(),
	description: text().notNull(),
});

export const reportTransaction = mysqlTable("report_transaction", {
	reportId: int("report_id").autoincrement().notNull(),
	date: varchar({ length: 128 }).notNull(),
	income: varchar({ length: 128 }).notNull(),
	expenditure: varchar({ length: 128 }).notNull(),
	remark: text().notNull(),
	created: int().notNull(),
});

export const roleGroup = mysqlTable("role_group", {
	id: int().autoincrement().notNull(),
	roleId: int("role_id").notNull(),
	roleName: text("role_name").notNull(),
	remark: text().notNull(),
	profitSharing: int("profit_sharing").notNull(),
});

export const roleManagement = mysqlTable("role_management", {
	roleId: int("role_id").autoincrement().notNull(),
	showCustomer: int("show_customer").notNull(),
	addCustomer: int("add_customer").notNull(),
	editCustomer: int("edit_customer").notNull(),
	delCustomer: int("del_customer").notNull(),
	showItem: int("show_item").notNull(),
	addItem: int("add_item").notNull(),
	editItem: int("edit_item").notNull(),
	delItem: int("del_item").notNull(),
	showBill: int("show_bill").notNull(),
	addBill: int("add_bill").notNull(),
	delBill: int("del_bill").notNull(),
	showCoverage: int("show_coverage").notNull(),
	addCoverage: int("add_coverage").notNull(),
	editCoverage: int("edit_coverage").notNull(),
	delCoverage: int("del_coverage").notNull(),
	coverageOperator: int("coverage_operator").notNull(),
	showSlide: int("show_slide").notNull(),
	addSlide: int("add_slide").notNull(),
	editSlide: int("edit_slide").notNull(),
	delSlide: int("del_slide").notNull(),
	showRouter: int("show_router").notNull(),
	addRouter: int("add_router").notNull(),
	editRouter: int("edit_router").notNull(),
	delRouter: int("del_router").notNull(),
	showSaldo: int("show_saldo").notNull(),
	showIncome: int("show_income").notNull(),
	addIncome: int("add_income").notNull(),
	editIncome: int("edit_income").notNull(),
	delIncome: int("del_income").notNull(),
	showUser: int("show_user").notNull(),
	editUser: int("edit_user").notNull(),
	delUser: int("del_user").notNull(),
	addUser: int("add_user").notNull(),
	showProduct: int("show_product").notNull(),
	addProduct: int("add_product").notNull(),
	editProduct: int("edit_product").notNull(),
	delProduct: int("del_product").notNull(),
	showUsage: int("show_usage").notNull(),
	showHistory: int("show_history").notNull(),
	showSpeedtest: int("show_speedtest").notNull(),
	showLog: int("show_log").notNull(),
	cekBill: int("cek_bill").notNull(),
	cekUsage: int("cek_usage").notNull(),
	showHelp: int("show_help").notNull(),
	editHelp: int("edit_help").notNull(),
	delHelp: int("del_help").notNull(),
	addHelp: int("add_help").notNull(),
	registerCoverage: int("register_coverage").notNull(),
	registerMaps: int("register_maps").notNull(),
	registerShow: int("register_show").notNull(),
	coverageTeknisi: int("coverage_teknisi").notNull(),
	customerFree: int("customer_free").notNull(),
	customerIsolir: int("customer_isolir").notNull(),
	editBill: int("edit_bill").notNull(),
	confirmBill: int("confirm_bill").notNull(),
	addOdc: int("add_odc").notNull(),
	editOdc: int("edit_odc").notNull(),
	delOdc: int("del_odc").notNull(),
	addOdp: int("add_odp").notNull(),
	editOdp: int("edit_odp").notNull(),
	delOdp: int("del_odp").notNull(),
	addMidi: int("add_midi").notNull(),
	editMidi: int("edit_midi").notNull(),
	delMidi: int("del_midi").notNull(),
	addVoip: int("add_voip").notNull(),
	editVoip: int("edit_voip").notNull(),
	delVoip: int("del_voip").notNull(),
	addGsm: int("add_gsm").notNull(),
	editGsm: int("edit_gsm").notNull(),
	delGsm: int("del_gsm").notNull(),
	addItemInventori: int("add_item_inventori").notNull(),
	editItemInventori: int("edit_item_inventori").notNull(),
	delItemInventori: int("del_item_inventori").notNull(),
	addVendor: int("add_vendor").notNull(),
	editVendor: int("edit_vendor").notNull(),
	delVendor: int("del_vendor").notNull(),
	payBill: int("pay_bill").notNull(),
});

export const roleMenu = mysqlTable("role_menu", {
	roleId: int("role_id").notNull(),
	customer: int().notNull(),
	customerMenu: int("customer_menu").notNull(),
	customerAdd: int("customer_add").notNull(),
	customerActive: int("customer_active").notNull(),
	customerNonActive: int("customer_non_active").notNull(),
	customerWaiting: int("customer_waiting").notNull(),
	customerWhatsapp: int("customer_whatsapp").notNull(),
	customerChart: int("customer_chart").notNull(),
	customerMaps: int("customer_maps").notNull(),
	servicesMenu: int("services_menu").notNull(),
	servicesAdd: int("services_add").notNull(),
	servicesItem: int("services_item").notNull(),
	servicesCategory: int("services_category").notNull(),
	coverage: int().notNull(),
	coverageAdd: int("coverage_add").notNull(),
	coverageMenu: int("coverage_menu").notNull(),
	coverageMaps: int("coverage_maps").notNull(),
	bill: int().notNull(),
	billMenu: int("bill_menu").notNull(),
	billUnpaid: int("bill_unpaid").notNull(),
	billPaid: int("bill_paid").notNull(),
	billDueDate: int("bill_due_date").notNull(),
	billDraf: int("bill_draf").notNull(),
	billDebt: int("bill_debt").notNull(),
	billConfirm: int("bill_confirm").notNull(),
	billCodeCoupon: int("bill_code_coupon").notNull(),
	billHistory: int("bill_history").notNull(),
	billDelete: int("bill_delete").notNull(),
	billSend: int("bill_send").notNull(),
	financeMenu: int("finance_menu").notNull(),
	financeIncome: int("finance_income").notNull(),
	financeExpend: int("finance_expend").notNull(),
	financeReport: int("finance_report").notNull(),
	help: int().notNull(),
	helpMenu: int("help_menu").notNull(),
	helpCategory: int("help_category").notNull(),
	router: int().notNull(),
	routerMenu: int("router_menu").notNull(),
	routerCustomer: int("router_customer").notNull(),
	routerSchedule: int("router_schedule").notNull(),
	websiteMenu: int("website_menu").notNull(),
	websiteSlide: int("website_slide").notNull(),
	websiteProduct: int("website_product").notNull(),
	user: int().notNull(),
	userMenu: int("user_menu").notNull(),
	userAdd: int("user_add").notNull(),
	userAdmin: int("user_admin").notNull(),
	userOperator: int("user_operator").notNull(),
	userTeknisi: int("user_teknisi").notNull(),
	userMitra: int("user_mitra").notNull(),
	userOutlet: int("user_outlet").notNull(),
	userCustomer: int("user_customer").notNull(),
	userKolektor: int("user_kolektor").notNull(),
	userFinance: int("user_finance").notNull(),
	roleMenu: int("role_menu").notNull(),
	roleAccess: int("role_access").notNull(),
	roleSubMenu: int("role_sub_menu").notNull(),
	integrationMenu: int("integration_menu").notNull(),
	integrationWhatsapp: int("integration_whatsapp").notNull(),
	integrationEmail: int("integration_email").notNull(),
	integrationTelegram: int("integration_telegram").notNull(),
	integrationSms: int("integration_sms").notNull(),
	integrationPaymentGateway: int("integration_payment_gateway").notNull(),
	integrationOlt: int("integration_olt").notNull(),
	integrationRadius: int("integration_radius").notNull(),
	settingMenu: int("setting_menu").notNull(),
	settingCompany: int("setting_company").notNull(),
	settingAboutCompany: int("setting_about_company").notNull(),
	settingBankAccount: int("setting_bank_account").notNull(),
	settingTermsCondition: int("setting_terms_condition").notNull(),
	settingPrivacyPolicy: int("setting_privacy_policy").notNull(),
	settingLogs: int("setting_logs").notNull(),
	settingBackup: int("setting_backup").notNull(),
	settingOther: int("setting_other").notNull(),
	customerFree: int("customer_free").notNull(),
	customerIsolir: int("customer_isolir").notNull(),
	integrationBriva: int("integration_briva").notNull(),
	integrationMoota: int("integration_moota").notNull(),
	masterMenu: int("master_menu").notNull(),
	masterOdc: int("master_odc").notNull(),
	masterOdp: int("master_odp").notNull(),
	roleGroup: int("role_group").notNull(),
	mapsMenu: int("maps_menu").notNull(),
	mapsCustomer: int("maps_customer").notNull(),
	mapsCoverage: int("maps_coverage").notNull(),
	mapsOdc: int("maps_odc").notNull(),
	mapsOdp: int("maps_odp").notNull(),
	masterStatuscustomer: int("master_statuscustomer").notNull(),
	masterBranddevice: int("master_branddevice").notNull(),
	masterScript: int("master_script").notNull(),
});

export const router = mysqlTable("router", {
	id: int().autoincrement().notNull(),
	isActive: int("is_active").notNull(),
	alias: varchar({ length: 50 }).notNull(),
	ipAddress: text("ip_address").notNull(),
	username: varchar({ length: 20 }).notNull(),
	password: varchar({ length: 100 }).notNull(),
	port: int().notNull(),
	dateReset: int("date_reset").notNull(),
	createBy: int("create_by").notNull(),
	routerMitra: int("router_mitra").notNull(),
});

export const script = mysqlTable("script", {
	id: int().autoincrement().notNull(),
	name: text().notNull(),
	vendor: text().notNull(),
	onuType: text("onu_type").notNull(),
	script: text().notNull(),
});

export const services = mysqlTable("services", {
	servicesId: int("services_id").autoincrement().notNull(),
	email: varchar({ length: 50 }).notNull(),
	itemId: int("item_id").notNull(),
	categoryId: int("category_id").notNull(),
	noServices: varchar("no_services", { length: 125 }).notNull(),
	qty: varchar({ length: 128 }).notNull(),
	price: varchar({ length: 128 }).notNull(),
	disc: varchar({ length: 128 }).default('NULL'),
	total: varchar({ length: 128 }).notNull(),
	remark: text().notNull(),
	servicesCreate: int("services_create").notNull(),
	createBy: int("create_by").notNull(),
},
(table) => [
	index("item_id").on(table.itemId),
	index("category_id").on(table.categoryId),
]);

export const slide = mysqlTable("slide", {
	slideId: int("slide_id").autoincrement().notNull(),
	name: varchar({ length: 225 }).notNull(),
	picture: text().notNull(),
	description: text().notNull(),
	link: text().notNull(),
	createBy: int("create_by").notNull(),
});

export const smsGateway = mysqlTable("sms_gateway", {
	smsId: int("sms_id").autoincrement().notNull(),
	smsName: text("sms_name").notNull(),
	smsUrl: text("sms_url").notNull(),
	smsToken: text("sms_token").notNull(),
	smsUser: text("sms_user").notNull(),
	smsPassword: text("sms_password").notNull(),
	smsApiKey: text("sms_api_key").notNull(),
	isActive: int("is_active").notNull(),
	smsVendor: text("sms_vendor").notNull(),
	smsCreateinvoice: int("sms_createinvoice").notNull(),
	smsPaymentinvoice: int("sms_paymentinvoice").notNull(),
	smsDuedateinvoice: int("sms_duedateinvoice").notNull(),
	smsInterval: int("sms_interval").notNull(),
	smsReminderinvoice: int("sms_reminderinvoice").notNull(),
	smsSender: text("sms_sender").notNull(),
	smsTimeStart: text("sms_time_start").notNull(),
	smsTimeEnd: text("sms_time_end").notNull(),
	textBill: text("text_bill").notNull(),
	textPayment: text("text_payment").notNull(),
	textDuedate: text("text_duedate").notNull(),
	textAddCustomer: text("text_add_customer").notNull(),
});

export const theme = mysqlTable("theme", {
	id: int().autoincrement().notNull(),
	userId: int("user_id").notNull(),
	darkMode: int("dark_mode").notNull(),
	navActive: text("nav_active").notNull(),
	primaryColor: text("primary-color").notNull(),
});

export const timezone = mysqlTable("timezone", {
	timezid: int().autoincrement().notNull(),
	tz: varchar({ length: 255 }).notNull(),
	gmt: text().notNull(),
});

export const user = mysqlTable("user", {
	id: int().autoincrement().notNull(),
	email: varchar({ length: 128 }).notNull(),
	password: varchar({ length: 100 }).notNull(),
	name: varchar({ length: 128 }).notNull(),
	phone: varchar({ length: 25 }).notNull(),
	address: text().notNull(),
	image: varchar({ length: 225 }).notNull(),
	roleId: text("role_id").notNull(),
	isActive: int("is_active").notNull(),
	dateCreated: int("date_created").notNull(),
	gender: varchar({ length: 10 }).notNull(),
	noServices: varchar("no_services", { length: 50 }).notNull(),
	fee: int().notNull(),
	ppn: varchar({ length: 40 }).notNull(),
	pph: varchar({ length: 40 }).notNull(),
	bhp: varchar({ length: 40 }).notNull(),
	uso: varchar({ length: 40 }).notNull(),
	admin: varchar({ length: 40 }).notNull(),
	feeActive: varchar("fee_active", { length: 40 }).notNull(),
	feeMitra: varchar("fee_mitra", { length: 50 }).notNull(),
	lang: text().notNull(),
});

export const userToken = mysqlTable("user_token", {
	id: int().autoincrement().notNull(),
	type: int().notNull(),
	email: varchar({ length: 128 }).notNull(),
	token: varchar({ length: 128 }).notNull(),
	dateCreated: int("date_created").notNull(),
});

export const whatsapp = mysqlTable("whatsapp", {
	id: int().autoincrement().notNull(),
	isActive: int("is_active").notNull(),
	apiKey: text("api_key").notNull(),
	token: text().notNull(),
	domainApi: text("domain_api").notNull(),
	username: varchar({ length: 50 }).notNull(),
	vendor: varchar({ length: 128 }).notNull(),
	createinvoice: int().notNull(),
	paymentinvoice: int().notNull(),
	duedateinvoice: int().notNull(),
	intervalMessage: int("interval_message").notNull(),
	sender: varchar({ length: 128 }).notNull(),
	reminderinvoice: int().notNull(),
	version: int().notNull(),
	period: int().notNull(),
	createHelp: text("create_help").notNull(),
	updateHelp: text("update_help").notNull(),
	getHelp: text("get_help").notNull(),
	createHelpCustomer: int("create_help_customer").notNull(),
	createHelpAdmin: int("create_help_admin").notNull(),
	idDevices: int("id_devices").notNull(),
	textHelpCustomer: int("text_help_customer").notNull(),
	sendHelpCustomer: int("send_help_customer").notNull(),
	official: int().notNull(),
	countBlast: int("count_blast").notNull(),
	lastExcute: text("last_excute").notNull(),
	timeStart: text("time_start").notNull(),
	timeEnd: text("time_end").notNull(),
	sendIsolir: int("send_isolir").notNull(),
});

export const whatsappSchedule = mysqlTable("whatsapp_schedule", {
	id: int().autoincrement().notNull(),
	target: text().notNull(),
	message: text().notNull(),
	customerId: int("customer_id").notNull(),
	invoiceId: text("invoice_id").notNull(),
	dateExcute: text("date_excute").notNull(),
	typeMessage: text("type_message").notNull(),
	createBy: int("create_by").notNull(),
	created: int().notNull(),
	remark: text().notNull(),
	status: text().notNull(),
	typeBill: text("type_bill").notNull(),
	dateCreated: text("date_created").notNull(),
	vendor: text().notNull(),
});
